AEFeinstein/Super-2024-Swadge-FW

main/display/shapes.c
This pull request fixes a bug in `drawLineInner()` that causes it to scale dashed lines by `yOffset` rather than `yScale`. In the case of a call to the regular unscaled `drawLine()` function , this means that the line's endpoint is always drawn at `y=0`.
To test, try drawing a dashed and regular line and seeing that they both draw in the correct place.
=> Fix drawLine() being drawn at incorrect y when dashWidth is non-zero

tools/font_maker/src/fontmaker.c
It allows you to have many more options when selecting a font size.
=> Allow fonter to use non-integer-font-heights.

main/menu/menu.c, main/menu/menu.h, main/menu/menuLogbookRenderer.c, main/modes/mainMenu/mainMenu.c, main/utils/settingsManager.c
This adds the multi-option settings item menu item as described in #33.
Testing:
1. Open the main menu
2. Go to settings
3. Scroll down to **Screensaver** and change the settings by scrolling left or right.
4. Make sure scrolling past the ends doesn't break anything and wraps correctly.
5. Go to the main menu and open some other mode (pong)
6. Go back to the settings menu and check that the screensaver setting is correct.
Closes #33
=> Mapped menu items

main/menu/menu.c, main/modes/mainMenu/mainMenu.c
In the main menu mode, when the BGM and SFX settings are changed, sound begins playing. However, after scrolling away from the settings, sound continues playing forever, until the mode is changed or something else plays sound.
This PR addresses that issue by stopping the buzzer whenever the menu item changes. In order to do that, `::menuCb` in `menu.c` was updated to now call the callback when scrolling between menu items, so that the callback can actually stop the buzzer.
On the main menu, go to Settings, then scroll down to BGM or SFX. Change the setting value and note the sound playing, then scroll to a different menu item (not BGM or SFX). The sound should stop playing.
Also, scroll around the other settings and general menu things and see that nothing is behaving strangely due to the …
=> Fix main menu buzzing forever

main/menu/menu.c, main/menu/menu.h
Confusion was mitigated
Compiled and tested on emulator and hardware
=> Fix confusing parameter name in `menuButton`

Doxyfile, docs/PORTING.md, main/swadge2024.c
Created documentation on porting 2023 Swadge modes.
Replicates documentation from #41, and closes the issue.
> This complains that `\ref setup`, `\ref contribution guide` and `\ref porting` can't be resolved. All these links are missing from my `index.html`. I'm not sure how I broke this, or how to fix it.
=> Porting docs

.github/workflows/build-firmware-and-emulator.yml, docs/SETUP.md, emulator/src/extensions/emu_args.c, emulator/src/getopt_win.h, makefile
This adds arg parsing with a standalone `getopt_win.h` provided by @cnlohr as well as some extra code to make the help text automatically just like our dear departed argp did.
I ran it a few times, changed around some options, things seemed mostly fine.
=> All the arg parsing, none of the dependencies

emulator/idf-inc/esp_sleep_emu.h, emulator/src/emu_main.c, emulator/src/emu_main.h, emulator/src/extensions/emu_args.c, emulator/src/extensions/emu_args.h, emulator/src/extensions/emu_ext.c, emulator/src/extensions/fuzzer/ext_fuzzer.c, emulator/src/extensions/fuzzer/ext_fuzzer.h, emulator/src/extensions/modes/ext_modes.c, emulator/src/extensions/modes/ext_modes.h, emulator/src/idf/esp_sleep.c
Fuzzing is back! New features and command-line args are:
* Changing start mode: `-m | --mode NAME`
* Switching modes periodically: `--mode-switch [TIME]`
* Listing modes and exiting: `--modes | --modes-list`
* Locking to start mode: `-l | -lock`
* Enable fuzzing everything: `--fuzz`
* Control fuzzing buttons/touch/accelerometer: `--fuzz-(buttons|touch|motion) [y/n]`
* Mix and match: `--fuzz --fuzz-motion=no`
Build the emulator.
Try invoking the emulator with these options and confirm its behavior:
* `--help` - Prints a very pretty help text, which also includes all the fuzzing and mode options, then exits.
* `--modes-list` - Prints a list of all the swadge mode names, then exits.
* `--fuzz` - Should print out a message to indicate buttons, touch, and accel are being fuzzed, then the main …
=> Fuzzer Emu Extension

.gitignore, emulator/src/emu_main.c, emulator/src/extensions/emu_args.c, emulator/src/extensions/emu_args.h, emulator/src/extensions/emu_ext.c, emulator/src/extensions/emu_ext.h, emulator/src/extensions/modes/ext_modes.c, emulator/src/extensions/modes/ext_modes.h, emulator/src/extensions/replay/ext_replay.c, emulator/src/extensions/replay/ext_replay.h
This adds functionality to the emulator for recording inputs to a file and playing them back later. It also supports some extra non-input actions when playing back a recording, such as enabling fuzzing, saving a screenshot, force-changing modes, and exiting the emulator.
Oh, and it adds a headless argument to have a hidden window, but I'm not sure if that works outside of Linux / for all rawdraw drivers.
Record inputs by running `swadge_emulator --record recording.csv` or just `swadge_emulator --record` (which should name the file `rec-xxxxxxx.csv`). When you're done, close the emulator and the file should now be full of inputs!
Play back that file with `swadge_emulator --playback recording.csv` and it should do exactly the same things as when recorded.
Edit the recording, and try adding …
=> Record/Playback Emulator Inputs

main/modes/pushy/pushy.c
Fixes this compile error that happens in main:
```
main/modes/pushy/pushy.c: In function ‘showDigit’:
main/modes/pushy/pushy.c:493:30: error: ‘%1u’ directive output may be truncated writing between 1 and 3 bytes into a region of size 2 [-Werror=format-truncation=]
493 |     snprintf(numberAsStr, 2, "%1" PRIu8, number);
|                              ^~~~
main/modes/pushy/pushy.c:493:31: note: format string is defined here
493 |     snprintf(numberAsStr, 2, "%1" PRIu8, number);
main/modes/pushy/pushy.c:493:30: note: directive argument in the range [0, 255]
493 |     snprintf(numberAsStr, 2, "%1" PRIu8, number);
|                              ^~~~
main/modes/pushy/pushy.c:493:5: note: ‘snprintf’ output between 2 and 4 bytes into a destination of size 2
493 |     snprintf(numberAsStr, 2, …
```
=> Fix too small buffer compile error

emulator/src/extensions/emu_args.c, emulator/src/extensions/emu_ext.c, emulator/src/extensions/keymap/ext_keymap.c, emulator/src/extensions/keymap/ext_keymap.h, main/swadge2024.c, main/swadge2024.h
Adds an extension that lets you use the emulator with several alterate keyboard layouts, for mostly selfish reasons:
* AZERTY
* Colemak
* Dvorak
Run the emulator with --keymap 'azerty' or -k dvorak  or -k colemak and see that it uses different keybindings.
=> Keymap Emulator Extension

main/menu/menu.c
Fixes a bug where selecting a menu item with `PB_A` or going up with `PB_B` would call the callback, but not change menu levels properly (but using left and right would).
On the main menu, scroll down to Settings and press A. It should open the settings menu. In the settings menu, press B and you should go back to the main menu.
=> Fix missing return messing up menus

components/hdw-nvs/hdw-nvs.c, components/hdw-nvs/include/hdw-nvs.h, emulator/src/components/hdw-nvs/hdw-nvs.c
Adds just the additional namespaced NVS functions as well as their emulator counterparts.  This PR doesn't change the usage of the existing NVS functions, which should continue to work identically.
I've only really tested the blob and entry info functions within paint on the emulator. Assuming further testing will be done as a result of moving modes to use the functions.
#52 
- [x ] I have run `make cppcheck` and checked that `cppcheck_result.txt` has no warnings for the changes
=> Namespaced NVS functions

components/hdw-bzr/hdw-bzr.c, components/hdw-bzr/include/hdw-bzr.h, components/hdw-led/hdw-led.c, components/hdw-led/include/hdw-led.h, components/hdw-tft/hdw-tft.c, components/hdw-tft/include/hdw-tft.h, emulator/src/components/hdw-bzr/hdw-bzr.c, emulator/src/components/hdw-led/hdw-led.c, emulator/src/components/hdw-tft/hdw-tft.c, emulator/src/emu_main.c, main/modes/mainMenu/mainMenu.c, main/modes/quickSettings/quickSettings.c, main/swadge2024.c, main/utils/settingsManager.c
Fixes a couple settings-related issues I noticed while working on real hardware, and adds a bit more polish to quick and regular settings.
Fixed issues:
* TFT and LED brightness settings didn't actually apply until you changed them after boot, since they initialize after reading the settings and would only use defaults.
* BGM was played with SFX volume on hardware
Enhancements:
* Quick settings menu now does an LED pattern while setting LED brightness
* Added feature to save and restore the buzzer state, so quick settings doesn't reset the underlying mode's music
* Quick settings menu plays sound while changing volume (does not work, at all -- seems to be an issue with quick settings specifically, or I am doing something dumb)
* Main menu settings only play sounds when levels are changed, …
=> Fix settings gripes

components/hdw-imu/CMakeLists.txt, components/hdw-imu/hdw-imu.c, components/hdw-imu/include/hdw-imu.h, components/hdw-imu/include/quaternions.h, components/hdw-imu/quaternions.c, emulator/src/components/hdw-imu/hdw-imu.c, emulator/src/components/hdw-imu/quaternions.c
Standalone math functions for quaternions, vectors, etc. are moved from `hdw-imu.c` into a separate file that can be copied wholesale between the swadge and the emulator.
Run the accel test on both the emulator and the swadge, the math should at least match up now even if the emulator doesn't really do anything.
=> Reorganize IMU and quaternion math functions

emulator/src/extensions/touch/ext_touch.c
Keyboard keys 1-4 will now trigger the touchpad.
`./swadge-emulator -t -m Touch` and see if 1-4 work
=> Make keys 1-4 in the emulator trigger the touchpad

main/menu/menu.c
Tested with the graphics test mode currently in the `3d-rendering-api` branch, but it's pretty easy to stick it in the main menu or something and see if it crashes.
=> Fix use-after free in removeSingleItemFromMenu()

emulator/src/extensions/touch/ext_touch.c
* Always enables touchpad for keys 1-4, regardless of if the emulator touchpad is displayed
* Adds support for 8-way touch when holding multiple keys, as though it were a D-pad
Test by pressing keys 1-4. 8-way touch can be tested by rolling through pairs 13, 34, 42, and 21 to go through a full rotation in 45-degree increments.
=> Always handle touchpad keys

main/modes/dance/dance.c
Fixes the math in the light dances to make the touchpad work for all speeds, and makes it relative using the spins API. Also fixes the text to say "Spins" instead of "Y~X"
Open light dances mode, spin the touchpad around in both directions. It should rotate from 1/8x to 4x with one full rotation.
=> Fix touchpad functionality and text in light dances

components/hdw-led/hdw-led.c, components/hdw-led/include/hdw-led.h, emulator/src/components/hdw-led/hdw-led.c, main/modes/dance/dance.c, main/modes/mainMenu/mainMenu.c, main/swadge2024.c, main/swadge2024.h
Added screensaver timeout from main menu.
Added light sleep during LED animations.
* Must be run on actual hardware
* Wait on the main menu to enter LED animation mode
* Wait on LED animation mode to turn off the display
* Make sure the LED behavior is sane when the display is off
n/a
=> Screensaver

emulator/src/extensions/emu_args.c
Everyone just yelled at me to do it, so I did it. Better late than never...
=> Enable touch by default

emulator/src/components/hdw-imu/hdw-imu.c, main/modes/slideWhistle/slideWhistle.c
Added new steering wheel input code for input in Techno Slide Whistle, fixed issue with touchpad input that allowed for out of bounds notes to play.
=> Fixed bug with touchpad on Techno Slide Whistle, added new steering angle code

components/hdw-usb/hdw-usb.c, tools/sandbox_test/sandbox.c, tools/sandbox_test/usbhid_test/Makefile, tools/sandbox_test/usbhid_test/sandbox.S, tools/sandbox_test/usbhid_test/sandbox.c, tools/sandbox_test/usbhid_test/test/Makefile, tools/sandbox_test/usbhid_test/test/hidtest.c
This makes it possible to use advanced USB modes with custom descriptors at a later time, alleviating need for special usb modes now.
This includes logic that Bryce and I talked about over the jam, but there was a misunderstanding.  So I added it here.
It also does a bit of an odd thing, appending past the end of the descriptor array, these values will not be reference-able, however, they are here, so that that can be referenced by sandbox tools.
=> Make usb usable for advanced modes

components/hdw-usb/hdw-usb.c, emulator/idf-inc/tinyusb.h, main/asset_loaders/common/heatshrink_encoder.c, main/asset_loaders/common/heatshrink_encoder.h, main/display/shapes.c, main/modes/gamepad/gamepad.c, main/modes/mfpaint/paint_browser.c, main/modes/mfpaint/paint_canvas.c, main/modes/mfpaint/paint_gallery.c, main/modes/mfpaint/paint_share.c, main/modes/timer/modeTimer.c, main/utils/wheel_menu.c
Make USB descriptors const
Fix emu tinyusb.h to match actual
Make heatshrink_encoder_sink() ingest const data
Only do framebuffer tricks in shapes.c for __XTENSA__ Only qsort() non-empty arrays
Fix possible null pointer in _paintSerialize()
Remove unused variables
Un-shadow variables
Don't mix pointer types
Use correct declaration for qsort comparator
Fixed various warnings
Compile without warnings (emu, fw)
Run cppcheck & ignore alloca() warnings
n/a
=> Fix various warnings

main/modes/ray/ray_death_screen.c, main/modes/ray/ray_pause.c, main/modes/ray/ray_renderer.c
* Draw "Game Over" on the game over screen
* Updated game over text
* Don't invert the boss's colors when using X-Ray visor
* Don't use `clearPxTft()` (may fix phantom text, maybe not?)
Played the game, died
n/a
=> Magtroid game over

main/menu/menu.c, main/menu/menu.h, main/modes/mfpaint/paint_common.h, main/modes/mfpaint/paint_draw.c, main/utils/wheel_menu.c
Fixes the brush size wheel not working at all, as reported by @Brycey92. Just needed to actually call the callback properly.
Try to change the brush size in paint.
=> Fix brush size in paint

main/modes/jukebox/jukebox.c
The sounds have been reordered to attempt to tell a story, or to display them in the order you might encounter them in the games. Lumber Jacks respawn and game over were moved to SFX so they don't loop.
=> Fix Jukebox typos, reorder music and SFX within categories

main/modes/flight/flight.c, main/modes/mainMenu/mainMenu.c
Fix null reference that sometimes happens when entering flight sim mode if you aren't first to the party (only happens about 10% of the time) but if near the portal will happen close to 95+% of the time.
Also, use a new slot for text as to not override what text already was, since the existing swadges squawk out an annoying message all the time.
=> Fix flight sim for portal

docs/SETUP.md, emulator/src/components/hdw-esp-now/hdw-esp-now.c, emulator/src/emu_main.c, emulator/src/rawdraw_sf.h, emulator/src/sound/sound_pulse.c, main/modes/flight/flight.c, main/modes/mfpaint/paint_nvs.h, main/modes/mfpaint/paint_ui.c, main/modes/mfpaint/px_stack.c, main/modes/quickSettings/menuQuickSettingsRenderer.c, main/utils/dialogBox.c, main/utils/macros.h, main/utils/touchTextEntry.c, main/utils/wheel_menu.c, makefile, tools/font_maker/makefile, tools/spiffs_file_preprocessor/makefile, tools/spiffs_file_preprocessor/src/heatshrink_util.c, tools/spiffs_file_preprocessor/src/spiffs_file_preprocessor.c
[Problem]
Attempting to build on a MacOS device currently fails due to a variety of issues. This includes:
- Referencing "malloc.h"
- Missing checks for Apple compiler flags
- Incompatible compiler and linker flags for MacOS' clang gcc version
- The ARRAY_SIZE macro not being compatible with the MacOS' clang gcc version
- Incompatible sound library (asound)
[Solution]
This change fixes the above issues and updates the documentation for how to use on MacOS. Sound currently is a work in progress as a new sound library is searched for to use.
Built and confirmed that the simulator runs in XQuartz now, ensuring that a few different games are up and running.
=> Initial MacOS Support

emulator/src/components/hdw-esp-now/hdw-esp-now.c, emulator/src/components/hdw-nvs/cJSON.h, emulator/src/emu_main.c, tools/hidapi.c, tools/spiffs_file_preprocessor/src-lib/cJSON.h, tools/spiffs_file_preprocessor/src/spiffs_file_preprocessor.c
I've replaced a ton of preprocessor OS detections in rawdraw, cnfa, and the swadge repo. However, I didn't replace all of them, especially where it looked like the author was intentionally not using all possible environment variable names (that they knew of) to detect a certain OS.
This fixes an issue where `make usbflash` fails to work on Windows with the current toolchain.
Respective PRs for the submodules can be found here for [rawdraw](https://github.com/cntools/rawdraw/pull/106) and [cnfa](https://github.com/cntools/cnfa/pull/23).
As a warning, I've only tested this in a Windows Cygwin environment, so other environments and OSes still need to be tested.
`make format` failed with the following error:
```Error reading /cygdrive/d/Bryce/Documents/MAGFest/Swadge-2024/Swadge-IDF-5.0/.clang …
```
=> Use more environment variables for OS detection

.gitignore, .vscode/launch.json, docs/SETUP.md, emulator/src/emu_main.c, emulator/src/extensions/keymap/ext_keymap.c
Made all the necessary fixes and changes to be able to launch and debug the Swadge Emulator on macOS from the comfort of your own VS Code.
Previously you needed to manually launch the Swadge Emulator from a separate XQuartz terminal window. Also, it was not possible to debug. 
Follow the revised instructions in the documentation and this should be handled automatically with the `(lldb) Launch` configuration, except for the step to launch the pulseaudio service.\.
clean emulator
Run without Debuggin (with `(lldb) Launch` configuration selected)
=> Macos dev fixes

main/display/wsg.c
This fixes the issue with  `drawWsgSimpleScaled()` described in #228. When the Y-offset is negative, the drawing of the line is skipped but the pointer to the WSG data isn't advanced, so instead the image is drawn at Y=0, and however many lines should have been skipped drawing at the beginning are skipped at the end instead.
Test by drawing some scaled WSGs with a negative Y offset and making sure they're drawn correctly.
Closes #228
=> Fix drawWsgSimpleScaled() misbehaving on negative Y assets. Fixes #228

main/modes/system/quickSettings/menuQuickSettingsRenderer.c
Update the colors of the quick settings menu to better match the mania menu renderer.
:eye: :eye:
=> Re-style quick settings to match mania menu

main/modes/test/keebTest/keebTest.c, main/modes/test/keebTest/keebTest.h, main/utils/textEntry.c, main/utils/textEntry.h
textEntry.h now supports a prompt and setting the initial text entry mode.
Tested in emulator.
Tested on swadge hardware.
#251
=> More keyboard funcs

main/utils/textEntry.c
Fixed issue #253, Capslock and shift not functioning as expected.
1. Run ./swadge-emulator -m "Keyboard Test"
2. Enter text entry
3. Type in at least one character
4. Set caps mode, set shift mode, observe how the text does not capitalize
#253
=> Fixed text capitialization condition to allow Capslock to work

.github/workflows/build-firmware-and-emulator.yml, emulator/src/emu_main.c, main/utils/textEntry.c, makefile, tools/spiffs_file_preprocessor/src/raw_processor.c
Contains standalone fixes for OSX from the midi-synth-platform-midi branch.
Tested on the midi-synth-platform-midi branch and with an updated workflow that builds for OSX also.
=> Standalone OSX Build Fixes

main/modes/system/intro/introMode.c
Fixes the incorrect buttons and accompanying text in the Tutorial mode.
Use your eyes and compare it with a Swadge. I think it matches this time!
=> Fix incorrect buttons in Tutorial mode

components/hdw-imu/hdw-imu.c
Accel was being brought up too quickly potentially having incorrect settings to boot.
Experimentally by looking at the I2C bus
=> Fix delay on accelerometer bringup. Found out we needed more time.

main/asset_loaders/fs_font.c, main/asset_loaders/heatshrink_helper.c, main/utils/cnfs.c, main/utils/cnfs.h
This change lets you load files without needing to copy their contents.
This change should be transparent but improve performance.
=> CNFS - Use file references where it makes sense.

emulator/src/extensions/tools/ext_tools.c
Fixes screen recording GIFs playing back slowly due to using inconsistently supported 10ms frame times. Will occasionally drop frames from the GIF to ensure the timing is reasonably accurate even when the actual frame rate does not fit evenly within 10ms increments.
Do some screen recordings, upload them to slack or open them in a browser, and see if they work OK and have the right playback speed. Check modes that have different frame rates also.
=> Fix GIF speed and don't use times below 20ms

.github/workflows/build-firmware-and-emulator.yml, .github/workflows/static.yml, docs/EMULATOR.md, makefile
* The CI process was updated to automatically create a new github release called "snapshot" whenever changes are merged to main.
* The Windows build now uses static `pthread` instead of linking against the shared `libwinpthread-1`, so including `libwinpthread-1.dll` in the artifact is no longer necessary!
* Minor updates to documentation to reflect changes.
* Finally using msys2 action with caching for Windows (I ended up switching the order of the firmware / emulator as suggested). Now it's almost a whole minute faster!
Here's an example from my fork of what this will create: https://github.com/dylwhich/Swadge-IDF-5.0/releases/tag/snapshot.
Before merging, you can download the artifacts from the action (or from the last run on my fork) and check that all the files are there. You should …
=> Create snapshot release with downloads when merging into main

emulator/src/components/hdw-nvs/hdw-nvs.c, emulator/src/emu_utils.c
Just making a draft PR to see if this builds
=> Switch _mkdir() to CreateDirectory()

docs/EMULATOR.md, emulator/src/components/hdw-nvs/hdw-nvs.c, emulator/src/components/hdw-nvs/hdw-nvs_emu.h, emulator/src/emu_cnfs.c, emulator/src/emu_cnfs.h, emulator/src/emu_main.c, emulator/src/extensions/emu_args.c, emulator/src/extensions/emu_args.h, emulator/src/extensions/emu_ext.c, emulator/src/extensions/midi/ext_midi.c, emulator/src/extensions/midi/ext_midi.h, makefile
Adds the ability to open a MIDI file with `--midi-file <filename>`, which starts the emulator in the `MIDI Player` mode and does some magic to inject the MIDI File contents into a fake CNFS entry. You can also omit the `--midi-file` argument and pass the MIDI file as the last argument, which should make dragging a MIDI file onto the executable Just Work to open things on Windows at least.
- Use `--midi-file` to start the emulator with a specific MIDI file
- Try to open a nonexistent file with `--midi-file` and check that the error message makes sense
- Try dragging a MIDI file onto the executable (on Windows)
=> Emulator MIDI File Opening

Doxyfile, docs/EMULATOR.md, docs/MIDI.md, main/swadge2024.c
Adds a dedicated page with more detailed technical documentation for the swadge's MIDI support.
`make docs` and read
=> Add MIDI technical documentation

docs/MIDI.md
Fixed broken markdown table formatting and html entities.
=> Fix broken markdown

.github/workflows/build-firmware-and-emulator.yml, docs/EMULATOR.md, emulator/resources/SwadgeEmulator.desktop, emulator/resources/install.sh
Adds a [FreeDesktop .desktop file](https://wiki.archlinux.org/title/Desktop_entries) for the Linux emulator, and a script to be included with the emulator download that handles installing it and its related files.
It works on my machine! The install script should work if you run it from the download (with `swadge_emulator`, `icon.png`, and `SwadgeEmulator.desktop`), the repository root, or the `emulator/resources` directory inside the repository. If you try to run it from somewhere else it should complain about the files and give you a hint to fix it, and exit without doing anything else. Installing to alternate locations, e.g. `/usr/local`, should work and instructions are included in the emulator docs. On probably most Linux desktop environments (tested on Gnome), after installing you …
=> Add FreeDesktop config files for native support in graphical desktop environments

docs/MIDI.md, emulator/src/idf/midi_device.c, main/midi/midiFileParser.c, main/midi/midiPlayer.c, main/midi/midiPlayer.h, main/modes/music/usbsynth/mode_synth.c
Adds support for setting MIDI registered and non-registered parameters. Mostly these aren't supported but non-registered parameters are the one place we can stick custom commands without registering a SysEx ID with the MMA.
Also adds support for "Universal SysEx" commands that are non-manufacturer-specific and defined in the MIDI standard.  Only the General MIDI Enable/Disable commands are supported now.
Adds the GM Enable/Disable setting to the MIDI Player mode, and also switches the mode to using SPIRAM for everything.
And finally, the default instruments are changed to be the chiptune-y MAGFest sounds, pre-selected on channels to match the MIDI file template, and all this included in the docs.
Tested using the switch in the MIDI player mode as well as using test MIDI files for [GM …
=> MIDI Registered/Non-registered Parameter Support, default instrument changes

emulator/resources/Info.plist, emulator/src/extensions/midi/ext_midi.c, makefile, tools/mac_events_test/.gitignore, tools/mac_events_test/Info.plist, tools/mac_events_test/main.c, tools/mac_events_test/makefile
=> Attempt to add direct MIDI-opening support for OSX

main/modes/games/ultimateTTT/ultimateTTT.c, main/modes/games/ultimateTTT/ultimateTTTgame.c, main/modes/games/ultimateTTT/ultimateTTTresult.c
Fix LEDs for CPU moves, result screen
Play a bunch of single system UTTT games and make sure you always have your selected marker
Make sure LED color matches the player during CPU matches and on the result screen.
n/a
=> Use the player's marker for 2p local system

main/modes/games/bigbug/mode_bigbug.c
Removed X parallax from background draw.
The gradient can't be `memcpy()`'d because it isn't screen with. The semi-transparent layer can't be `memcpy()`'d either. Everything is turbo-pixeled.
Run bigbug and watch the background
#345
=> #345 Remove X parallax from background draw

main/display/wsg.c, main/display/wsg.h, main/display/wsgPalette.c, main/display/wsgPalette.h, main/modes/games/ultimateTTT/ultimateTTTgame.c
Fixed sprites clipping while rotated
Play UTTT, make sure sprites don't clip while rotating
#349
=> Fix rotation

main/modes/games/cGrove/Garden/cg_Grove.c
Fixed C-Stick in the Chowa "Grove" mode.
Ran emulator, Chowa grove, main grove mode with C stick controls enabled. Moves stick around in all directions.
None. Hotfix.
=> Fixed C stick controls fort Chowa

main/modes/games/cGrove/Garden/cg_GroveAI.c
[Problem]
When multiple Chowa hatch in the same frame, only the first one to hatch is able to be named since the others won't trigger the state changes.
[Solution]
Ensure we stop processing Chowa states until after the names have been entered.
[Testing]
Confirmed working with 2 and 3 Chowa hatching at the same time.
Fixing issue #364 
Tested hatching multiple Chowa at the same time (2 and 3)
https://github.com/AEFeinstein/Super-2024-Swadge-FW/issues/364
=> Fix Chowa Name Race Condition

main/modes/games/2048/2048_game.c, main/modes/games/2048/mode_2048.c, main/modes/games/2048/mode_2048.h
Improve 2048 game motion controls.
By playing on a swadge (Though admittedly an early prototype)
N/A
- [N/A] I have added doxygen comments to any code used by more than one Swadge mode. This includes `/*! \file` comments with Design Philosophy, Usage, and Example sections for new headers.
- [N/A] I have run `make docs` and checked that `doxy_warnings.txt` has no warnings for the new code
=> Improve 2048 motion controls

main/modes/test/bongoTest/bongoTest.c
Fixed the notes getting stuck on.
Emulator: Attempted to reproduce bug, was unable to hear the screaming.
Hardware: Attempted to reproduce bug, was unable to hear the screaming.
#374
=> BBB update to stop the screaming.

main/display/font.c, main/display/font.h, main/modes/games/soko/sokoHelp.c, main/modes/games/swadgeHero/swadgeHero_game.c, main/modes/games/swadgeHero/swadgeHero_gameEnd.c
* Added `drawTextWordWrapCentered()`, refactored `drawTextWordWrapFlags()`
* Wrap & center long song names in Swadge Hero
* Clean Hunter Puzzle text
* Don't overdraw fail chart at the end of the song
* Fix phantom pause presses during Swadge Hero
* Play "Dance of the Cremulons" in Swadge Hero, see that text wraps nicely (except for menu title)
* View wrapped text elsewhere 
* tutorial
* UTTT instructions
* Hunter Puzzle instructions
* Sequencer instructions
* 2048 load
* Bigbug dialog
* Chowa Grove tutorials
n/a
=> Swadge hero fixes

docs/EMULATOR.md, emulator/src/extensions/emu_ext.c, emulator/src/extensions/fuzzer/ext_fuzzer.c, emulator/src/extensions/fuzzer/ext_fuzzer.h, emulator/src/extensions/replay/ext_replay.c, emulator/src/extensions/replay/ext_replay.h, emulator/src/extensions/tools/emu_console_cmds.c, emulator/src/extensions/tools/ext_tools.c, emulator/src/extensions/tools/ext_tools.h
* Adds the option to only fuzz certain buttons when fuzzing
* Adds a bunch of console commands to the emulator, mainly ones to control fuzzing
* Adds the ability to include a console command within a replay script CSV
* Documents all the existing and new console commands
* Adds a slightly more advanced help to the console
* Fixes a bug with the emulator where hiding and showing panes on the fly didn't work properly
Try some console commands, maybe try including a console command in a replay script.
=> More Console Commands and Replay Script Support

emulator/src/extensions/emu_ext.c, emulator/src/extensions/emu_ext.h, emulator/src/extensions/gamepad/ext_gamepad.c, emulator/src/extensions/gamepad/ext_gamepad.h
Joystick inputs! They work on Windows and Linux, I haven't attempted OSX at all.
On both platforms, the joystick must be connected before the emulator starts. If the joystick is disconnected, the emulator will not attempt to reconnect to it.
Also in support of arcade-y things, I fixed the emulator display not being centered properly in fullscreen and some other situations that come up more often now that the LEDs have moved.
It's more or less plug and play! On Windows, will open the first joystick device available. On Linux, will open `/dev/input/js0`.
1. Plug in a swadge to USB
2. Open up Gamepad mode and start in Computer mode
3. Start the emulator
4. It should Just Work!
5. Try the Touch Test and Accel Test modes, and also everything else.
6. Open the emulator in fullscreen
=> Joystick input for Windows & Linux

components/hdw-usb/hdw-usb.c, tools/sandbox_test/buildhelp.c
The only change to this that matters is to hdw-usb.c,
1. Exposing two variables to the linker, for controlling advancedUsbHandler and setSwadgeMode, and
2. Including a uprintf call when logging is overridden to expose uprintf to the sandbox, regardless of logging levels.
Also, it includes a fix for some of the sandbox code but that doesn't release.
=> Needed changes to be able to use sandbox.

tools/assets_preprocessor/src/bin_processor.c, tools/assets_preprocessor/src/chart_processor.c, tools/assets_preprocessor/src/fileUtils.c, tools/assets_preprocessor/src/fileUtils.h, tools/assets_preprocessor/src/font_processor.c, tools/assets_preprocessor/src/image_processor.c, tools/assets_preprocessor/src/json_processor.c, tools/assets_preprocessor/src/raw_processor.c, tools/assets_preprocessor/src/rmd_processor.c, tools/assets_preprocessor/src/txt_processor.c
Basically, this fixes having to ever run `make fullclean`, because I constantly forget and waste too much time trying to fix imaginary problems. It also fixes the inconsistency of some assets always being recreated and some never being recreated. This does change the `doesFileExist()` implementation to one that doesn't create the file if it doesn't exist, because I wanted to check in multiple places. Eventually I want to refactor the asset preprocessor a bit to unify all the boilerplate so that can go back but that's a later thing.
Adds a utility function to the assets preprocessor for checking whether one file is newer than another. All asset processors now only process an asset if either the destination does not exist, or if the source file is newer than the destination file. Basically …
=> Smarter file preprocessing

main/modes/games/ultimateTTT/ultimateTTTgame.c
Fixes the difficulty being lost when the CPU player data is reset.
Try hard mode and see if it's actually hard.
=> Fix TTT CPU Difficulty Selector

makefile
Fixes a couple things that bothered me just now.
1. Prioritize `clang-format-17` over the default one, because my new laptop is on a new fedora which comes with `clang-format` 19, which of course disagrees with 17 so I have to keep changing the makefile.
2. Add a separate makefile target for `wget plantuml.jar` instead of running it in `make docs`. Not sure why, but every time I ran `make docs` it would print a message saying plantuml.jar was already present and won't be downloaded, but then it downloaded it anyway.
Tested by running `make format` and `make docs` on several different machines with different versions of stuff. Seemed to work fine to me!
=> Minor makefile fixes

main/modes/games/pango/paSoundManager.c, main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c, main/modes/games/ultimateTTT/ultimateTTTgame.c, main/modes/utilities/gamepad/gamepad.c
Fixes the subgame selection algorithm of the hard TTT AI to prioritize winning the game over winning a subgame when the game can be won multiple ways.
Adds a function that just does a `checkWin()` against a copy of the game board with a hypothetical move, and uses that to check every possible move in the select subgame algorithm for hard mode. This seems fast enough, I haven't noticed any issues with it on hardware.
Also fixes the yellow 'next subgame' animation square remaining visible at its last location when a new game is started. In order for it to show up, you have to finish a game then start another, and it would be there.
Tested by playing some hard games. In particular it had trouble with the situation where these subgames are already won, with the bottom-right subgame being one …
=> Fix TTT Hard AI Subgame Selection

emulator/src/extensions/replay/ext_replay.c, emulator/src/extensions/tools/emu_console_cmds.c, main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c, main/modes/system/intro/introMode.c
Fix a couple warnings plus a logic error, and a line I deleted and accidentally broke the replay extension with.
=> Fix warnings and the replay extension

main/modes/utilities/gamepad/gamepad.c
If you exit gamepad by hitting Start & Select at the _exact same time_, you'll get an event with `(PB_START | PB_SELECT)` as the value, and it doesn't trigger the condition at all.
Tested with a swadge in gamepad mode.
=> Fix gamepad not exiting if Menu/Pause are pressed at the exact same time

main/modes/games/bigbug/gameData_bigbug.c
Be in the middle of a level in big bug and try to exit. Sometimes it hangs forever
=> Fix infinite loop when exiting BigBug

README.md, docs/DESIGN_PRINCIPLES.md, docs/EMULATOR.md, docs/SERIAL_DEBUG.md, docs/SETUP.md, emulator/README.md, main/swadge2024.c
Typos and some simple fixes. Nothing major, but I did add some missing extensions and split them into necessary/unnecessary sections.
=> Docs - typos

main/CMakeLists.txt, makefile
Updates the makefile (and CMake file) to use the asset preprocessor timestamp file to avoid unnecessary recompilation.
`make` and `idf.py build` after modifying assets and C files, etc. Also you should be able to add a new file and a reference to it, and it should build without errors on the first try.
=> Fix unnecessary recompilation

main/utils/nameList.c
Added `setUsernameFromND(nd);`` to `setUsernameFrom32()`
Check second line in name test mode terminal print in not identical to first line.
None
=> Actually changing the username for setUsernameFrom32()

main/modes/music/swadgetamatone/swadgetamatone.c, main/modes/system/mainMenu/mainMenu.c
- Add a fourth octave and simplify octave logic
- Only open mouth when playing notes
- Animate mouth open/close when a note starts/stops
- Trophies!
1. Run the mode. Ensure the main menu trophy is granted.
2. Play a note. Ensure the first mode trophy is granted.
3. Play notes for at least 60 seconds to ensure the timed trophies work.
4. Play for another hour and ensure the other 2 timed trophies work if you want to be really thorough.
5. Test all of the d-pad buttons to ensure they all play different octaves.
https://github.com/AEFeinstein/Super-2024-Swadge-FW/issues/483
=> Swadgetamatone trophies and tweaks
