main/modes/pushy/pushy.c
Fixed #89.
Tested on both emu and hardware.
#89
=> Fix pushy checkWeed/checkRainbow

main/modes/lumberjack/lumberjack.c, main/modes/lumberjack/lumberjackGame.c
Use charactersArray in lumberjack_t
Don't use lumv after free
=> [Lumberjack] Fix more memory issues

components/hdw-btn/hdw-btn.c, main/modes/gamepad/gamepad.c
=> New hardware touch adj

components/hdw-imu/hdw-imu.c, components/hdw-imu/include/hdw-imu.h, components/hdw-imu/include/quaternions.h, components/hdw-imu/quaternions.c, main/modes/flight/flight.c, main/modes/flight/flight.h, makefile
* Add two more modes to flight controls.
* Add monitor to make options
=> Last leg for steering wheel, etc.

main/modes/flight/flight.c
Mostly just changing the way the flightsim does menus.
=> Tweak flightsim menus to update to the way we do menus.

main/modes/gamepad/gamepad.c
=> Switch gamepad touchpad map to left stick

main/modes/gamepad/gamepad.c, main/utils/settingsManager.c, main/utils/settingsManager.h
@JVeg199X tested on hardware and confirmed it's working
=> Gamepad touch setting

main/modes/credits/mode_credits.c, main/modes/mainMenu/mainMenu.c
Add credits and git hash
Reorder menus
=> Menu credits

main/modes/jukebox/jukebox.c
=> Reorder categories in Jukebox to match main menu

main/modes/breakout/breakout.c, main/modes/breakout/entity.c, main/modes/breakout/entityManager.c, main/modes/breakout/gameData.c, main/modes/breakout/gameData.h
=> Brickdown fixes - final?

main/modes/mfpaint/mode_paint.c, main/modes/mfpaint/paint_browser.c, main/modes/mfpaint/paint_browser.h, main/modes/mfpaint/paint_common.h, main/modes/mfpaint/paint_draw.c, main/modes/mfpaint/paint_draw.h, main/modes/mfpaint/paint_gallery.c, main/modes/mfpaint/paint_ui.c, main/utils/wheel_menu.c
All of Bryce's fixes rebased onto current main, plus I got rid of the green plus in the image title that shouldn't have made it into the final version.
Use paint, particularly the menu and saving and things, make sure there's no bugs.
=> Paint fixes (dylwhich's version)

main/modes/quickSettings/quickSettings.c
Mask frambuffer glitch by redrawing entire quick settings screen
Test entering quick settings in breakout, magtroid, and lumberjacks on real hardware
#176
=> Copy framebuffer & redraw bg for quick settings

main/modes/mainMenu/mainMenu.c, main/modes/tunernome/tunernome.c, main/utils/settingsManager.c, main/utils/settingsManager.h
=> Less fucky secrets

main/modes/jukebox/jukebox.c
=> Add Credits category to Jukebox UI

.github/workflows/build-firmware-and-emulator.yml
Only runs the slack notification step once, after everything else succeeds.
Let's see here...
=> Fix the build spam!

docs/EMULATOR.md
Fixing a broken link
Click the link!
=> Fix broken link in EMULATOR.md

tools/sandbox_test/usbhid_test/sandbox.c, tools/sandbox_test/usbhid_test/test/Makefile, tools/sandbox_test/usbhid_test/test/hidtest.c, tools/sandbox_test/usbhid_test/test/winbuild.bat
This was something from a long time ago but lets the test use 255-byte HID requests.  Useful for things like radio mode.
=> Update demo code for usb hid demo

main/modes/system/intro/introMode.c, main/modes/test/factoryTest/factoryTest.c
Update factory test for new hardware
Run through the factory test, noting the text
#315
=> Factory test

main/modes/games/2048/2048_game.c, main/modes/games/2048/2048_game.h, main/modes/games/2048/mode_2048.c, main/modes/games/2048/mode_2048.h
You can now save in 2048.
Emulator. Video in [Slack](https://magfest.slack.com/archives/C6FNXU6KX/p1735690628549709?thread_ts=1735619424.866459&cid=C6FNXU6KX).
#360
=> 2048 saves

main/modes/system/intro/introMode.c
Fix weird grammar typo
Not tested, made it on GitHub. But what's the worst that could happen...
=> Fix typo in intro touchpad text
